# Generated by Django 3.2.8 on 2021-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors_img', verbose_name='Photo of the author')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name="Author's description")),
                ('nationality', models.CharField(blank=True, choices=[('VEN', 'Venezolano'), ('ESP', 'Español'), ('COL', 'Colombiano'), ('PER', 'Peruano')], max_length=3, null=True, verbose_name="Author's nationality")),
                ('sex', models.CharField(blank=True, choices=[('MAN', 'Man'), ('WOM', 'Woman'), ('???', '???')], max_length=3, null=True, verbose_name='Gender')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autors',
            },
        ),
    ]
