# Generated by Django 3.2.8 on 2021-11-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='relationship',
            name='author_rela_from_us_05e825_idx',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='from_user',
            field=models.CharField(max_length=100, verbose_name='usuario que sigue'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='to_user',
            field=models.CharField(max_length=100, verbose_name='usuario al que siguen'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
