# Generated by Django 3.2.8 on 2021-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20211113_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='facebook link'),
        ),
        migrations.AddField(
            model_name='author',
            name='twiter',
            field=models.URLField(blank=True, null=True, verbose_name='facebook link'),
        ),
    ]
