# Generated by Django 3.2.8 on 2021-11-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
