# Generated by Django 3.2.8 on 2021-11-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_remove_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='background_photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors_back_img', verbose_name='background photo of the profile author'),
        ),
    ]
