# Generated by Django 3.2.8 on 2021-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_author_background_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='big_description',
            field=models.TextField(blank=True, null=True, verbose_name='big description'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
