# Generated by Django 3.2.8 on 2021-11-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_auto_20211107_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, choices=[('VEN', 'Venezolano/a'), ('ESP', 'Español/a'), ('POR', 'Portugues/a'), ('COL', 'Colombiano/a'), ('PER', 'Peruano/a'), ('MEX', 'Mexicano/a'), ('CHI', 'Chileno/a'), ('ARG', 'Argentino/a'), ('000', 'Otro')], max_length=3, null=True, verbose_name="Author's nationality"),
        ),
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.CharField(blank=True, choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('PLA', 'Plátano'), ('000', 'Otro')], max_length=3, null=True, verbose_name='Gender'),
        ),
    ]
