# Generated by Django 3.2.8 on 2021-11-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='stars',
            field=models.IntegerField(choices=[('1', 'una estrella'), ('2', 'dos estrellas'), ('3', 'tres estrellas'), ('4', 'cuatro estrellas'), ('5', 'cinco estrellas')]),
        ),
    ]
