# Generated by Django 3.2.8 on 2021-11-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.CharField(max_length=255),
        ),
    ]
