# Generated by Django 3.2.8 on 2021-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_star_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='stars',
            field=models.IntegerField(choices=[(1, 'Una'), (2, 'Dos'), (3, 'Tres'), (4, 'Cuatro'), (5, 'Cinco')]),
        ),
    ]
