# Generated by Django 3.2.8 on 2021-11-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_star_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='stars',
            field=models.IntegerField(choices=[(1, 'Una Estrella'), (2, 'Dos Estrellas'), (3, 'Tres Estrellas'), (4, 'Cuatro Estrellas'), (5, 'Cinco Estrellas')]),
        ),
    ]
