# Generated by Django 3.2.8 on 2021-10-31 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_alter_book_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='autor',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(choices=[('1', 'one star'), ('2', 'Two stars'), ('3', 'Three stars'), ('4', 'Four stars'), ('5', 'Five stars')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'verbose_name': 'Star',
                'verbose_name_plural': 'Stars',
            },
        ),
    ]
